### ISSUE TITLE
SQL error when attempting to manually set up fleet sides.

### ISSUE THREAD

**Issue by Nuramori** [Salvoxia/fleet_battles_mod#1]
When attempting to manually set up the battle "sides", clicking on save will generate a SQL error as follows:

"Database error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
SQL: REPLACE INTO kb3_battles_owner_pilots (battle_id, plt_id) VALUES (8, )"

Example: http://kb.tiod.wtf/index.php/kill_related/1225/battle/

Choosing "setup" then "switch" to move a participant to the other side, then clicking "save" will generate the error above.

**Comment by Salvoxia** [comment]
Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Nuramori** [comment]
The issue persists.   The error for the particular battle I chose to "setup" resulted with :

Database error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
SQL: REPLACE INTO kb3_battles_owner_pilots (battle_id, plt_id) VALUES (1, )

I had attempted in dropping then creating the database, with the problem continuing.   I am also running on fedora 26, which by default uses mariadb.    

I will export and copy you a database within the hour.  

Regards,
Ed

**Comment by Nuramori** [comment]
Id be happy to.  I'll check what the permission setting are as well to make sure that there isn't an issue with that.

**Comment by Nuramori** [comment]
Interesting.   I did go back to an old fleet I initially attempted to fix manually, and it was in fact showing at the top that it had previously been manually fixed, and subsequently it now will work.   All other initial battles that upon the very first attempt to correct will generate the error.

**Comment by Nuramori** [comment]
Here are the CSV exports for both tables, caching and the battle reports.




On Jun 04, 2017, at 02:07 PM, Salvoxia <notifications@github.com> wrote:

Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Nuramori** [comment]
Ok, I think I may have found WHERE the error happens?  Based n your comments I parsed the code, and in class.battles.php beginning at line 273 (where it sets up the sql line), it has :

 $sql = "UPDATE kb3_battles_cache SET
                        killIsk = {$killIsk},
                        lossIsk = {$lossIsk},
                        efficiency = {$efficiency},
                        bar = '{$barGenerated}',
                        kills = {$kills},
                        losses = {$losses},
                        involved = {$involved},
                        start = '{$timestampStart}',
                        end = '{$timestampEnd}',
                        ownersInvolved = {$numberOfOwnersInvolved}
                     WHERE battle_id = {$battleId}";

Now, based on the ACTUAL cache table entry, the one entry that's NOT covered in that sql command is "kll_id".  I don't see where that table entry has a value in the coding to be included in the command.

Regards,
Ed


On Jun 04, 2017, at 02:07 PM, Salvoxia <notifications@github.com> wrote:

Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Nuramori** [comment]
Ok, I got it to work now, but I get a server 500 error, BUT the sql seems to work when I return to the page.

I edited the class.battles.php with the following:

around line 244, after "         * @param int $battleId"
I added - "         * @param int $kllId"

I modified around line 255 to include the above, with "        public static function updateCacheForBattle($battleId, $kllId, $killIsk, $lossIsk, $kills, $losses, $involved, $timestampStart, $timestampEnd, $numberOfOwnersInvolved, $involvedOwnerIds)"

around line 275, after "            $sql = "UPDATE kb3_battles_cache SET"
I added "                        kll_id = {$kllId},"


This seems to make it work from a sql standpoint, but the page generation is now not working until I go back.  When I do so, it will correctly show the reassignment.


Edward Palisoc, NCARB RA
edp collaborative, LLC
6081 Endden Court
Norcross, Georgia  30092
404,783.1543
email:  ed.palisoc@edp-collaborative.com

On Jun 04, 2017, at 02:07 PM, Salvoxia <notifications@github.com> wrote:

Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Nuramori** [comment]
ok, It seems there's an odd conflict with another (and older mod called "augmented Banner".  When I turn that mod off, the modifications I made all work for fleet battles.
When I have augmented banner mod turned on, I get the following error in my logs.

Non-static method augmented_banner::add() should not be called statically in /var/www/tiod.wtf/kb/common/includes/class.event.php on line 71, referer: http://kb.tiod.wtf/index.php/settings_fleet_battles_mod/
There's that strange crossover I don't get, but otherwise the change works.



On Jun 04, 2017, at 02:07 PM, Salvoxia <notifications@github.com> wrote:

Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Nuramori** [comment]
Here is a zip file with the mod package on my system.  I saw a bunch of spelling errors too, a couple in variables that bothered my OCD :p.




On Jun 04, 2017, at 02:07 PM, Salvoxia <notifications@github.com> wrote:

Ah, that again.
It got reported here and there, but I was never successful in replicating that issue.
Some reported, that it was gone after a day with the same battle report, which points in the direction of a caching issue.
Now, that more than a day has passed, can you reliably replicate that problem? And if so, would you consider sending me an export of the relevant database tables?

**Comment by Salvoxia** [comment]
Hi,

thank you very much for your digging around. However, if you attached files to your mails, the attachments got eaten by github or something.
This still helped me to finally replicate the issue, find the cause and fix it.
The ultimate reason was a typo when checking whether a variable was initialized.
This lead to the variable being re-initialized, overwriting the previous content, triggering another problem with handling the variable if it was empty.
I'd be happy to include spelling corrections and such, if I can get my hands at that zip file. Maybe you could message it to me at the evekb.org Forums?
And could you please test whether the changes in the master branch solve the problem for you (download [here](https://github.com/Salvoxia/fleet_battles_mod/archive/master.zip)?

Thanks and best Regards,
Salvoxia


P.S.: The error with the augmented banner mod seems to be due to a compatibility problem with that mod and PHP 7.1.. :(

**Comment by Nuramori** [comment]
That's great!  Glad to help.    I'll try and get you the files shortly.  For some reason evekb.org seems to be down for me, but I'll check in later with it. 

While looking through my logs, I came across some deprecated php errors (same naming comment as before) in the display_ship_tools mod.  I'll get you some log wording too.

On Jun 04, 2017, at 06:12 PM, Salvoxia <notifications@github.com> wrote:

Hi,
thank you very much for your digging around. However, if you attached files to your mails, the attachments got eaten by github or something.
This still helped me to finally replicate the issue, find the cause and fix it.
The ultimate reason was a typo when checking whether a variable was initialized.
This lead to the variable being re-initialized, overwriting the previous content, triggering another problem with handling the variable if it was empty.
I'd be happy to include spelling corrections and such, if I can get my hands at that zip file. Maybe you could message it to me at the evekb.org Forums?
And could you please test whether the changes in the master branch solve the problem for you (download here?
Thanks and best Regards,
Salvoxia

**Comment by Nuramori** [comment]
Everything is working perfectly fine now.
If it wouldn't be too much trouble, could you help me with this old but very useful mod?

http://www.evekb.org/forum/viewtopic.php?f=505&t=18606&p=50218#p50218

I posted the error I am now getting.

On Jun 04, 2017, at 06:12 PM, Salvoxia <notifications@github.com> wrote:

Hi,
thank you very much for your digging around. However, if you attached files to your mails, the attachments got eaten by github or something.
This still helped me to finally replicate the issue, find the cause and fix it.
The ultimate reason was a typo when checking whether a variable was initialized.
This lead to the variable being re-initialized, overwriting the previous content, triggering another problem with handling the variable if it was empty.
I'd be happy to include spelling corrections and such, if I can get my hands at that zip file. Maybe you could message it to me at the evekb.org Forums?
And could you please test whether the changes in the master branch solve the problem for you (download here?
Thanks and best Regards,
Salvoxia
